# Generated by Django 2.1 on 2018-08-19 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    replaces = [('word_count', '0001_initial'), ('word_count', '0002_auto_20180817_0305'), ('word_count', '0003_auto_20180817_1703'), ('word_count', '0004_auto_20180818_1742')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(verbose_name='URL')),
                ('source', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_count.Page')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_count.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='wordcount',
            unique_together={('page', 'word')},
        ),
        migrations.AlterField(
            model_name='wordcount',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AlterModelTable(
            name='page',
            table='page',
        ),
        migrations.AlterModelTable(
            name='wordcount',
            table='word_count',
        ),
    ]
